#' Link coarseDataTools and EpiEstim
#'
#' This function is deprecated. Use [primary2estim()], which turns a serial
#' interval estimated with
#' [primarycensored][primarycensored::primarycensored-package] into a sample
#' of serial interval distributions for [estimate_R()].
#'
#' Transforms the output of `coarseDataTools::dic.fit.mcmc()` to the right
#' format for input into [estimate_R()] with method "si_from_sample".
#'
#' @param x An object generated by `coarseDataTools::dic.fit.mcmc()`,
#' containing posterior estimates of the serial interval distribution.
#' @param dist The parametric distribution used when estimating the serial
#' interval. Should be one of "gamma", "weibull", "lognormal", "gamma_offset_1",
#' "weibull_offset_1", or "lognormal_offset_1". If not present, computed
#' automatically from `x`.
#' @param samples A dataframe containing the posterior samples of serial
#' interval parameters corresponding to the parametric choice specified in
#' `dist`. If not present, computed automatically from `x`.
#' @param thin A positive integer corresponding to thinning parameter; of the
#' posterior sample of serial interval distributions in x, only 1 in `thin`
#'  will be kept, the rest will be discarded.
#'
#' @return A list with two elements:
#'   - `si_sample`: a matrix where each column gives one distribution of the
#'      serial interval to be explored, obtained from x by thinning the MCMC chain.
#'   - `si_parametric_distr`: the parametric distribution used when estimating
#' the serial interval stored in x.
#'
#' @seealso [primary2estim()]
#' @author The Hackout3 Parameter Estimation team.
#'
#' @export
coarse2estim <- function(x = NULL, dist = x@dist, samples = x@samples,
                         thin = 10) {
  .Deprecated(msg = paste(
    "coarse2estim() is deprecated. Use primary2estim() with a fit from",
    "primarycensored instead."
  ))
  if (is.null(x)) # then check that dist and samples are what we expect
  {
    rtn <- si_from_data_valid_distrs(dist)

    if (!rtn$is_dist_valid) {
      stop("The supported distributions are 'gamma', 'weibull',
           'lognormal', 'gamma_offset_1' (Gamma shifted by 1),
           'weibull_offset_1' (Weibull shifted by 1),
           or 'lognormal_offset_1' (Lognormal shifted by 1). ", call. = FALSE)
    }
    if (!is.data.frame(samples)) {
      stop("samples should be a dataframe, e.g. as produced in x@samples,
           where x is the output of coarseDataTools::dic.fit.mcmc().",
           call. = FALSE)
    }
  }

  if (thin > 1) {
    index <- seq(1, nrow(samples), thin)
    samples <- samples[index, ]
  }

  ## Discretise each serial interval distribution in the sample
  fit_distr <- si_fit_distr(dist)
  samples <- stats::setNames(as.data.frame(samples), fit_distr$params)
  prob_matrix <- primary2estim(
    samples, dist = fit_distr$pdist, shift = fit_distr$shift
  )$si_sample

  out <- list(si_sample = prob_matrix, si_parametric_distr = dist)

  return(out)
}
