#' Link coarseDataTools and EpiEstim
#'
#' \code{\link{coarse2estim}} Transforms outputs of
#' \code{\link[coarseDataTools]{dic.fit.mcmc}} to right format for input into
#' \code{\link{estimate_R}}
#'
#' @param x An object generated by function
#' \code{\link[coarseDataTools]{dic.fit.mcmc}}, containing posterior estimates of the
#' serial interval distribution.
#' @param dist The parametric distribution used when estimating the serial
#' interval. Should be one of "gamma", "weibull", "lognormal", "gamma_offset_1",
#'  "weibull_offset_1", or "lognormal_offset_1". Note the different naming 
#' convention compared to \code{\link[coarseDataTools]{dic.fit.mcmc}}. The
#' distribution may also be specified using the abbreviated forms "G", "W", "L",
#' "off1G", "off1W", and "off1L" as used in \code{\link[coarseDataTools]{dic.fit.mcmc}}.
#' However, we recommend using the full names to avoid confusion, and a warning
#' will be issued if the abbreviated forms are used.
#' If not present, computed automatically from \code{x}.
#' @param samples A dataframe containing the posterior samples of serial
#' interval parameters corresponding to the parametric choice specified in
#' `dist`. If not present, computed automatically from `x`.
#' @param thin A positive integer corresponding to thinning parameter; of the
#' posterior sample of serial interval distributions in x, only 1 in `thin`
#'  will be kept, the rest will be discarded.
#'
#' @return A list with two elements:
#'   - `si_sample`: a matrix where each column gives one distribution of the
#'      serial interval to be explored, obtained from x by thinning the MCMC chain.
#'   - `si_parametric_distr`: the parametric distribution used when estimating
#' the serial interval stored in x.
#'
#' @seealso [estimate_R()]
#' @author The Hackout3 Parameter Estimation team.
#'
#' @export
#' @examples
#' \dontrun{
#' ## Note the following examples use an MCMC routine
#' ## to estimate the serial interval distribution from data,
#' ## so they may take a few minutes to run
#'
#' ## load data on rotavirus
#' data("MockRotavirus")
#'
#' ## estimate the serial interval from data
#' SI.fit <- coarseDataTools::dic.fit.mcmc(
#'   dat = MockRotavirus$si_data,
#'   dist = "G",
#'   init.pars = init_mcmc_params(MockRotavirus$si_data, "G"),
#'   burnin = 1000,
#'   n.samples = 5000
#' )
#'
#' ## use coarse2estim to turn this in the right format for estimate_R
#' si_sample <- coarse2estim(SI.fit, thin = 10)$si_sample
#'
#' ## use estimate_R to estimate the reproduction number
#' ## based on these estimates of the serial interval
#' R_si_from_sample <- estimate_R(
#'   MockRotavirus$incidence,
#'   method = "si_from_sample",
#'   si_sample = si_sample,
#'   config = make_config(list(n2 = 50))
#' )
#' 
#' plot(R_si_from_sample)
#' }
#'
coarse2estim <- function(x = NULL, dist = x@dist, samples = x@samples,
                         thin = 10) {
  if (is.null(x)) # then check that dist and samples are what we expect
  {
    rtn <- si_from_data_valid_distrs(dist)

    if (!rtn$is_dist_valid) {
      stop("The supported distributions are 'gamma', 'weibull',
           'lognormal', 'gamma_offset_1' (Gamma shifted by 1),
           'weibull_offset_1' (Weibull shifted by 1),
           or 'lognormal_offset_1' (Lognormal shifted by 1). ")
    }
    if (!is.data.frame(samples)) {
      stop("samples should be a dataframe, e.g. as produced in x@samples,
           where x is the output of coarseDataTools::dic.fit.mcmc.")
    }
  }

  if (thin > 1) {
    index <- seq(1, nrow(samples), thin)
    samples <- samples[index, ]
  }
  n_samples <- nrow(samples)

  ##  Probability matrix that will be used in EpiEstim based on which
  ## distribution is specified by the user
  if (dist == "gamma"| dist == "G") {
    ## For each input parameter set, find the 99th percentile, and take the
    ## maximum of these as the maximum
    ## serial interval that we need to consider
    maxValue <- max(vnapply(seq_len(n_samples), function(i) 
      ceiling(stats::qgamma(0.999, shape = samples[i, 1], scale = samples[i, 2]))))
    max_interval <- seq_len(maxValue)
    prob_matrix <- apply(samples, 1, function(x) 
      stats::pgamma(max_interval + 0.5, shape = x[1], scale = x[2]) - 
        stats::pgamma(max_interval - 0.5, shape = x[1], scale = x[2]))
  } else if (dist == "weibull"| dist == "W") {
    maxValue <- max(vnapply(seq_len(n_samples), function(i) 
      ceiling(stats::qweibull(0.999, shape = samples[i, 1], scale = samples[i, 2]))))
    max_interval <- seq_len(maxValue)
    prob_matrix <- apply(samples, 1, function(x) 
      stats::pweibull(max_interval + 0.5, shape = x[1], scale = x[2]) - 
        stats::pweibull(max_interval - 0.5, shape = x[1], scale = x[2]))
  } else if (dist == "lognormal"| dist == "L") {
    maxValue <- max(vnapply(seq_len(n_samples), function(i) 
      ceiling(stats::qlnorm(0.999, meanlog = samples[i, 1], sdlog = samples[i, 2]))))
    max_interval <- seq_len(maxValue)
    prob_matrix <- apply(samples, 1, function(x) 
      stats::plnorm(max_interval + 0.5, meanlog = x[1], sdlog = x[2]) - 
        stats::plnorm(max_interval - 0.5, meanlog = x[1], sdlog = x[2]))
  } else if (dist == "gamma_offset_1"| dist == "off1G") {
    ## offset gamma distribution with shifted min and max value of max
    ## serial interval
    maxValue <- max(vnapply(seq_len(n_samples), function(i) 
      ceiling(stats::qgamma(0.999, shape = samples[i, 1], scale = samples[i, 2]))))
    max_interval <- seq(0, maxValue)
    prob_matrix <- apply(samples, 1, function(x) 
      stats::pgamma(max_interval + 0.5, shape = x[1], scale = x[2]) - 
        stats::pgamma(max_interval - 0.5, shape = x[1], scale = x[2]))
  } else if (dist == "weibull_offset_1"| dist == "off1W") {
    ## offset weibull distribution with shifted min and max value of max
    ## serial interval
    maxValue <- max(vnapply(seq_len(n_samples), function(i) 
      ceiling(stats::qweibull(0.999, shape = samples[i, 1], scale = samples[i, 2]))))
    max_interval <- seq(0, maxValue)
    prob_matrix <- apply(samples, 1, function(x) 
      stats::pweibull(max_interval + 0.5, shape = x[1], scale = x[2]) - 
        stats::pweibull(max_interval - 0.5, shape = x[1], scale = x[2]))
  } else if (dist == "lognormal_offset_1"| dist == "off1L") {
    ## offset lognormal distribution with shifted min and max value of max
    ## serial interval
    maxValue <- max(vnapply(seq_len(n_samples), function(i) 
      ceiling(stats::qlnorm(0.999, meanlog = samples[i, 1], sdlog = samples[i, 2]))))
    max_interval <- seq(0, maxValue)
    prob_matrix <- apply(samples, 1, function(x) 
      stats::plnorm(max_interval + 0.5, meanlog = x[1], sdlog = x[2]) - 
        stats::plnorm(max_interval - 0.5, meanlog = x[1], sdlog = x[2]))
  }
  
  # adding initial 0 for P(SI=0)
  prob_matrix <- rbind(rep(0, n_samples), prob_matrix)
  # renormalising
  prob_matrix <- apply(prob_matrix, 2, function(x) x / sum(x))

  out <- list(si_sample = prob_matrix, si_parametric_distr = dist)

  return(out)
}
